
# cargo-vet audits file

[[audits.anstream]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.anstyle]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.14"

[[audits.anstyle-parse]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.anstyle-query]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.1.5"

[[audits.anstyle-wincon]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "3.0.11"

[[audits.block-buffer]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.10.4"

[[audits.block-padding]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.3.3"

[[audits.cbc]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.1.2"

[[audits.cfg-if]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.4"

[[audits.clap]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "4.6.4"

[[audits.clap_builder]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "4.6.2"

[[audits.clap_derive]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "4.6.4"

[[audits.clap_lex]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.1.0"

[[audits.colorchoice]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.5"

[[audits.cpufeatures]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.2.17"

[[audits.crypto-common]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.1.7"

[[audits.des]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.8.1"

[[audits.digest]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.10.7"

[[audits.generic-array]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.14.7"

[[audits.hmac]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.12.1"

[[audits.inout]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.1.4"

[[audits.is_terminal_polyfill]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.70.2"

[[audits.itoa]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.18"

[[audits.libc]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.2.189"

[[audits.memchr]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.8.3"

[[audits.once_cell_polyfill]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.70.2"

[[audits.pbkdf2]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.12.2"

[[audits.proc-macro2]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.107"

[[audits.safe-read]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.serde]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.229"

[[audits.serde_core]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.229"

[[audits.serde_derive]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.229"

[[audits.serde_json]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.151"

[[audits.sha1]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.10.7"

[[audits.subtle]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.6.1"

[[audits.syn]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "3.0.3"

[[audits.thiserror]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.0.19"

[[audits.thiserror-impl]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "2.0.19"

[[audits.typenum]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.20.1"

[[audits.unicode-ident]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.24"

[[audits.version_check]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.9.5"

[[audits.windows-link]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.2.1"

[[audits.windows-sys]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "0.61.2"

[[audits.zmij]]
who = "Albert Hui <i@hack9u.online>"
criteria = "safe-to-deploy"
version = "1.0.23"
